name: CI
on:
  push:
permissions:
  contents: "read"
  repository-projects: "read"
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v6
      with:
        go-version: "1.26.5"
        cache: true
    - name: Build
      run: go build ./...
    - name: Test
      run: go test -race ./...
